# Form implementation generated from reading ui file 'designUI/lists.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtWidgets

from windows.horizontalTabBar import TabBar


class Ui_dialogLists(object):
    def setupUi(self, dialogLists):
        dialogLists.setObjectName("dialogLists")
        dialogLists.resize(675, 346)
        self.verticalLayout = QtWidgets.QVBoxLayout(dialogLists)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=dialogLists)
        self.tabWidget.setTabBar(TabBar(self.tabWidget))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.TabPosition.West)
        self.tabWidget.setObjectName("tabWidget")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=dialogLists)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(dialogLists)
        self.tabWidget.setCurrentIndex(-1)
        self.buttonBox.accepted.connect(dialogLists.accept) # type: ignore
        self.buttonBox.rejected.connect(dialogLists.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dialogLists)

    def retranslateUi(self, dialogLists):
        _translate = QtCore.QCoreApplication.translate
        dialogLists.setWindowTitle(_translate("dialogLists", "Списки"))
